# Generated by Django 3.1.4 on 2021-02-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='user_account',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='professionalinfo',
            old_name='user_account',
            new_name='user',
        ),
    ]
